### ISSUE TITLE
nukes dont finish launch sequence

### ISSUE THREAD

**Issue by nixtux** [ashdnazg/bos2cob#2]
Some scripts compiled with bos2cob dont fire, check https://github.com/n3wm1nd/TA/blob/master/scripts/tllsilo.bos
https://github.com/n3wm1nd/TA/blob/master/scripts/corsilo.bos

once compiled with scriptor there no issue

**Comment by ashdnazg** [comment]
this seems to be solved exactly like #3 (I've changed LINEAR_SCALE = 163840 and got binary same cob file)
