### ISSUE TITLE
move translated incorrectly

### ISSUE THREAD

**Issue by nixtux** [ashdnazg/bos2cob#3]
Does not seem to effect all scripts, there are a few more examples but not many

https://github.com/n3wm1nd/TA/blob/master/scripts/armanni.bos
https://dl.dropboxusercontent.com/u/200970/screen00215.jpg
Compiled with bos2cob on left, scriptor right

https://github.com/n3wm1nd/TA/blob/master/scripts/armlab.bos
compiled with bos2cob https://dl.dropboxusercontent.com/u/200970/screen00213.jpg
scriptor https://dl.dropboxusercontent.com/u/200970/screen00214.jpg

**Comment by ashdnazg** [comment]
it is translated correctly, but needs a different scale probably.
check what the linear scale is in scriptor and then set it to the same value to LINEAR_SCALE in bos2cob.py 
unfortunately, different .bos files were compiled with different scales, so you'll have to check what's the correct one in each script.

**Comment by nixtux** [comment]
Darn i thought i updated that. Must have missed it when updating, Thanks anyways

**Comment by ashdnazg** [comment]
no worries :)
